name: 'aws_data_platform'
version: '1.0.0'
config-version: 2

profile: 'redshift'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  aws_data_platform:
    +materialized: table
    +schema: analytics

    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging']

    marts:
      +materialized: table
      +schema: marts
      +tags: ['marts']

      dimensions:
        +materialized: table
        +tags: ['dimension']

      facts:
        +materialized: incremental
        +unique_key: 'id'
        +on_schema_change: 'append_new_columns'
        +tags: ['fact']

    cubes:
      +materialized: materialized_view
      +schema: cubes
      +tags: ['olap', 'cube']

vars:
  start_date: '2024-01-01'
  current_date: "{{ run_started_at.strftime('%Y-%m-%d') }}"

seeds:
  +schema: seeds
  +quote_columns: false
